Sarath.sfp_Dev_Org/src/objects/Document_Generation__c.object
<CustomObject>
    <description>Object will store the fields required for document process.</description>
    <fields>
        <fullName>Account_Number__c</fullName>
        <description>Field will store the account number populated from opportunity</description>
        <inlineHelpText>Field will store the account number populated from opportunity</inlineHelpText>
        <label>Account Number</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Con_Name__c</fullName>
        <label>Con Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Email__c</fullName>
        <description>This field will hold the customer email</description>
        <inlineHelpText>This field will hold the customer email</inlineHelpText>
        <label>Customer Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Customer_Fax__c</fullName>
        <description>This field will store the Customer fax</description>
        <inlineHelpText>This field will store the Customer fax</inlineHelpText>
        <label>Customer Fax</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <description>This field will hold the name of the customer</description>
        <inlineHelpText>This field will hold the name of the customer</inlineHelpText>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Phone__c</fullName>
        <description>This field will hold the value of the customer phone</description>
        <inlineHelpText>This field will hold the value of the customer phone</inlineHelpText>
        <label>Customer Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field will hold the opportunity value</description>
        <inlineHelpText>This field will hold the opportunity value</inlineHelpText>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Document_Generation</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Verified</fullName>
                </value>
                <value>
                    <fullName>Not verified</fullName>
                </value>
                <value>
                    <fullName>More Information required</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Forms</label>
    <nameField>
        <displayFormat>F-{00000000}</displayFormat>
        <label>Document Generation Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Forms</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Sarath.sfp_Dev_Org/src/classes/DocumentGenerationController.cls
Public without sharing class DocumentGenerationController{

    public Document_Generation__c doc{get;set;}
    public Id oppId {get;set;}
    public String oppName {get;set;}
    public blob file { get; set; }
    Public Attachment a{get;set;}
    Public Attachment myfile{get;set;}
    public boolean cmd{get;set;}
    public boolean cmd1{get;set;}

    Public Attachment b{get;set;}
    Public Attachment myfile1 {get;set;}
    
    public DocumentGenerationController(ApexPages.StandardController controller) {
        myfile1 = new Attachment();
        myfile =  new Attachment();
        cmd=false;
        cmd1=false;
        if (ApexPages.currentPage().getParameters().get('Id') != null){
            oppId = ApexPages.currentPage().getParameters().get('Id');  
            Opportunity oppRecord = new Opportunity();
            oppRecord = [Select Name,Id,Account.AccountNumber, Account.Name, Accountid
                         FROM opportunity
                         WHERE id=:oppId];
            if (oppRecord!=null){
                Contact con = new Contact();
                if (oppRecord.Accountid != null){
                    con = [Select id, name, phone, email, fax
                           FROM contact
                           WHERE accountid=:oppRecord.Accountid limit 1];
                }
                doc =  new Document_Generation__c();
                doc.Account_Number__c = oppRecord.Account.AccountNumber;
                doc.Opportunity__c = oppRecord.id;
                oppName = oppRecord.Name;
                doc.Customer_Name__c = oppRecord.Account.Name;
                if (con!=null){
                     doc.Con_Name__c = con.Name;
                    doc.Customer_Fax__c = con.Fax;
                    doc.Customer_Phone__c = con.Phone;
                    doc.Customer_Email__c = con.Email;
                }
            }
        }
    }
    
    public pageReference upload() {
        a = new Attachment();
        a.name = myfile.name;
        a.body = myfile.body;
        cmd=true;
        return null;
    }


    public pageReference upload1() {
        b = new Attachment();
        b.name = myfile1.name;
        b.body = myfile1.body;
        cmd1=true;
        return null;
    }
    public pageReference submitForm(){
        if (doc != null){
            doc.Status__c = 'Not verified';
            insert doc;
            if(doc.id !=null){
                Document_Generation__c  docGenerated = new Document_Generation__c();
                docGenerated = [Select id,name
                                FROM Document_Generation__c
                                WHERE id=:doc.id];
                List<Attachment> attList = new List<Attachment>();
                if(a!=null && a.body!=null && a.name!=null){
                    a.parentId = doc.id;
                    attList.add(a);
                }
                
                if(b!=null && b.body!=null && b.name!=null){
                    b.parentId = doc.id;
                     attList.add(b);
                }
                if (!attList.isEmpty()){
                    insert attList;
                }
                Pagereference pageref = new Pagereference('/apex/Form_Generation?id='+docGenerated.Name);  
                pageref.setRedirect(true);
                return pageref;   
            }
        }
        return null;
    }
    
    
}